/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author AsRock
 */
public class MenuUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form MenuUniversidad
     */
    public MenuUniversidad() {
        initComponents();
        this.setLocationRelativeTo(null);                                       //<---Para que centre el formulario principal en la panatalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDekPanEscritorio = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItmSalir = new javax.swing.JMenuItem();
        jMenuMaterias = new javax.swing.JMenu();
        jMenuItmMaterias = new javax.swing.JMenuItem();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItmAlumnos = new javax.swing.JMenuItem();
        jMenuInscripciones = new javax.swing.JMenu();
        jMenuItmManejoDeIncripciones = new javax.swing.JMenuItem();
        jMenuCargaDeNotas = new javax.swing.JMenu();
        jMenuItmManipulacionDeNotas = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItmListDeAlumnoXMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDekPanEscritorioLayout = new javax.swing.GroupLayout(jDekPanEscritorio);
        jDekPanEscritorio.setLayout(jDekPanEscritorioLayout);
        jDekPanEscritorioLayout.setHorizontalGroup(
            jDekPanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jDekPanEscritorioLayout.setVerticalGroup(
            jDekPanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItmSalir.setText("Salir");
        jMenuItmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItmSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItmSalir);

        jMenuBar.add(jMenuArchivo);

        jMenuMaterias.setText("Materias");

        jMenuItmMaterias.setText("Formulario de Materias");
        jMenuMaterias.add(jMenuItmMaterias);

        jMenuBar.add(jMenuMaterias);

        jMenuAlumnos.setText("Alumnos");

        jMenuItmAlumnos.setText("Formulario de Alumnos");
        jMenuAlumnos.add(jMenuItmAlumnos);

        jMenuBar.add(jMenuAlumnos);

        jMenuInscripciones.setText("Inscripciones");

        jMenuItmManejoDeIncripciones.setText("Manejo de Inscripciones");
        jMenuInscripciones.add(jMenuItmManejoDeIncripciones);

        jMenuBar.add(jMenuInscripciones);

        jMenuCargaDeNotas.setText("Carga de Notas");

        jMenuItmManipulacionDeNotas.setText("Manipulacion de Notas");
        jMenuCargaDeNotas.add(jMenuItmManipulacionDeNotas);

        jMenuBar.add(jMenuCargaDeNotas);

        jMenuConsultas.setText("Consultas");

        jMenuItmListDeAlumnoXMateria.setText("Listado de Alumnos x Materia");
        jMenuConsultas.add(jMenuItmListDeAlumnoXMateria);

        jMenuBar.add(jMenuConsultas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDekPanEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDekPanEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItmSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUniversidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUniversidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDekPanEscritorio;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCargaDeNotas;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuInscripciones;
    private javax.swing.JMenuItem jMenuItmAlumnos;
    private javax.swing.JMenuItem jMenuItmListDeAlumnoXMateria;
    private javax.swing.JMenuItem jMenuItmManejoDeIncripciones;
    private javax.swing.JMenuItem jMenuItmManipulacionDeNotas;
    private javax.swing.JMenuItem jMenuItmMaterias;
    private javax.swing.JMenuItem jMenuItmSalir;
    private javax.swing.JMenu jMenuMaterias;
    // End of variables declaration//GEN-END:variables
}
