/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.AlumnoData;
import Control.ConectarBD;
import Control.CursadaData;
import Control.MateriaData;
import Modelo.Alumno;
import Modelo.Cursada;
import Modelo.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AsRock
 */
public class VistaFormularioDeInscripcion extends javax.swing.JInternalFrame {
   
    //---ATRIBUTOS--------------------------------------------------------------
    
    private DefaultTableModel modelo;
    private CursadaData cursadaData;
    private Alumno alumnoSeleccionado;
    private Materia materiaElegida;
    ConectarBD conexion = new ConectarBD();
    
    
    
    //---CONSTRUCTOR------------------------------------------------------------
    public VistaFormularioDeInscripcion() {
        initComponents();
        
        modelo = new DefaultTableModel(){                                       
            @Override
            public boolean isCellEditable (int filas, int columnas){            //<---Metodo sobreescrito para que la talbla no sea editable
            
                    if(columnas == 4){
                        return true;
                    }else{
                        return false;
                    }
            }
        };
        
        llenarCombo();
        colocarTitulosTabla();
     
        
        jbtInscribir.setEnabled(false);
        jbtAnularInscripcion.setEnabled(false);
        jcbxAlumnos.setSelectedIndex(-1);
    }

    //**************************** METODOS *************************************
    //--------------------------------------------------------------------------

    
    
    private void borrarFilas(){
    
        //---CADA FILA EN LA EN EL MODELO, ES  UN AREGLO DE OBJETOS---
        
        int fila = (modelo.getRowCount() -1 ); //---tengo la pocision d ela ultima fila  
        
        // borramnos de atras para adelante 
        
        for (int i =  fila ; i >= 0 ; i-- ){
            
            modelo.removeRow(i);
        }
        
        
    }
    
    //--------------------------------------------------------------------------
    
    public void colocarTitulosTabla(){    
        
        ArrayList <Object> columnasTabla = new ArrayList<>();
        
        columnasTabla.add("Legajo");
        columnasTabla.add("Nombre");
        columnasTabla.add("Año");
      
        
        for(Object columnaIt: columnasTabla){
            
            modelo.addColumn(columnaIt);
        }
        
        jtableMaterias.setModel(modelo);
        
        
        
        
        
    }
    
    //-------------------------------------------------------------------------- 
    private void cargarTablaConMateriasInscriptas(){
    
        borrarFilas();
        
        alumnoSeleccionado = (Alumno) jcbxAlumnos.getSelectedItem();     //<---Alumno seleccionado ene l combobox    
        
        cursadaData = new CursadaData(conexion);
                                    
        ArrayList<Materia> listaMateriaInscriptas = cursadaData.obtenerMateriasIncriptas(alumnoSeleccionado.getId());
    
        for( Materia listMatInsIt : listaMateriaInscriptas){
        
             modelo.addRow(new Object[]{listMatInsIt.getId(), listMatInsIt.getNombre(),listMatInsIt.getAnio()});
        
        }
        
        
    }
    
    //-------------------------------------------------------------------------- 
    private void cargarTablaConMateriasNoInscriptas(){
    
        borrarFilas();
        
        alumnoSeleccionado = (Alumno) jcbxAlumnos.getSelectedItem();     //<---Alumno seleccionado en el combobox    
        
        cursadaData = new CursadaData(conexion);
                                    
        ArrayList<Materia> listaMateriaNoInscriptas = cursadaData.obtenerMateriasNoIncriptas(alumnoSeleccionado.getId());
    
        for( Materia listMatInsIt : listaMateriaNoInscriptas){
        
             modelo.addRow(new Object[]{listMatInsIt.getId(), listMatInsIt.getNombre(),listMatInsIt.getAnio()});
        
        }
        
        
    }
    //--------------------------------------------------------------------------    
    private void llenarCombo(){

        AlumnoData alumnoData = new AlumnoData(conexion);
        ArrayList <Alumno> alumnos = (ArrayList) alumnoData.listarAlumnos();
        
        for(Alumno aluIt: alumnos){
        
            jcbxAlumnos.addItem(aluIt);
        }
  
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbxAlumnos = new javax.swing.JComboBox<>();
        jlbAlumno = new javax.swing.JLabel();
        jlbFormularioDeInscripcion = new javax.swing.JLabel();
        jbtInscribir = new javax.swing.JButton();
        jbtAnularInscripcion = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMaterias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jradiobtNoInscriptas = new javax.swing.JRadioButton();
        jradiobtInscriptas = new javax.swing.JRadioButton();
        jlbListadoDeMaterias = new javax.swing.JLabel();

        setClosable(true);

        jcbxAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxAlumnosActionPerformed(evt);
            }
        });

        jlbAlumno.setText("Alumno");

        jlbFormularioDeInscripcion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlbFormularioDeInscripcion.setText("FORMULARIO DE INSCRIPCION");

        jbtInscribir.setText("Inscribir");
        jbtInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInscribirActionPerformed(evt);
            }
        });

        jbtAnularInscripcion.setText("Anular Inscripcion");

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jtableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableMaterias);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jradiobtNoInscriptas.setText("No Inscriptas");
        jradiobtNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobtNoInscriptasActionPerformed(evt);
            }
        });

        jradiobtInscriptas.setText("Inscriptas");
        jradiobtInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobtInscriptasActionPerformed(evt);
            }
        });

        jlbListadoDeMaterias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlbListadoDeMaterias.setText("LISTADO DE MATERIAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbListadoDeMaterias)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jradiobtInscriptas)
                        .addGap(43, 43, 43)
                        .addComponent(jradiobtNoInscriptas)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlbListadoDeMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jradiobtNoInscriptas)
                    .addComponent(jradiobtInscriptas))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbFormularioDeInscripcion)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jbtInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jlbAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbFormularioDeInscripcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAnularInscripcion)
                    .addComponent(jbtSalir)
                    .addComponent(jbtInscribir))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jradiobtInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobtInscriptasActionPerformed
        jbtInscribir.setEnabled(false);
        jbtAnularInscripcion.setEnabled(true);
        jradiobtNoInscriptas.setSelected(false);
        
        
        borrarFilas();
       
        if (jcbxAlumnos.getSelectedIndex() != -1){                              //<---Si hay un alumno sleeccionado
            cargarTablaConMateriasInscriptas();
        }else{
            JOptionPane.showMessageDialog(null," Debe seleccioanr un alumno");
            jcbxAlumnos.requestFocus();
        }
        
    }//GEN-LAST:event_jradiobtInscriptasActionPerformed

    private void jradiobtNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobtNoInscriptasActionPerformed
        jbtInscribir.setEnabled(true);
        jbtAnularInscripcion.setEnabled(false);
        jradiobtInscriptas.setSelected(false);
        borrarFilas();
        
        
        
        if (jcbxAlumnos.getSelectedIndex() != -1){                              //<---Si hay un alumno sleeccionado
            cargarTablaConMateriasNoInscriptas();
        }else{
            JOptionPane.showMessageDialog(null," Debe seleccioanr un alumno");
            jcbxAlumnos.requestFocus();
        }
        
    }//GEN-LAST:event_jradiobtNoInscriptasActionPerformed

    private void jcbxAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxAlumnosActionPerformed
        jradiobtInscriptas.setSelected(false);
        jradiobtNoInscriptas.setSelected(false);
        borrarFilas();
    }//GEN-LAST:event_jcbxAlumnosActionPerformed

    private void jtableMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMateriasMouseClicked
                                                                                //---En este Evento, selecciona una fila de la tabla 
            
            MateriaData materiaData = new MateriaData(conexion);
            
            // activar boton actualizar
            // activar boton borrar
            
            int filaSeleccionada = jtableMaterias.getSelectedRow();             //<---devuelve la fila seleccioanda
            
            if ( filaSeleccionada!= -1){                                        //<---Si la fila seleccionada, tiene un elemento seleccionado 
 
                int idMateriaSeleccionada = (Integer)jtableMaterias.getValueAt(filaSeleccionada, 0); //<---Lo que trae cada fila es de tipo Object. Hay que ir casteando (El primero elemento esta en la posicion 0, el segundo en el 1 y asi... como un arreglo)
                                                          
                materiaElegida = materiaData.buscarMateria(idMateriaSeleccionada); //<--- Con ese id, bucamos la materia y lo almacenamos en el atributo materiaElegida
            }
    }//GEN-LAST:event_jtableMateriasMouseClicked

    private void jbtInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInscribirActionPerformed
  
        Cursada cursada  = new Cursada(materiaElegida,alumnoSeleccionado,-1,true); //<--- -1 significa que todavia no tiene nota
         
        cursadaData = new CursadaData(conexion);
        
        if (cursadaData.guardarIncripcion(cursada)){
            JOptionPane.showMessageDialog(null," La Cuarsada fue guardada Satisfactorioamente!");
        }else{
            JOptionPane.showMessageDialog(null," No se pudo guardar la inscripcion!");
        }
         
        jcbxAlumnos.setSelectedIndex(-1);                                       //<---el combo que sin seleccion
        borrarFilas();                                                          //<---La tabla se limpia
        jcbxAlumnos.requestFocus();                                             //<---El foco queda en el combo 
    }//GEN-LAST:event_jbtInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAnularInscripcion;
    private javax.swing.JButton jbtInscribir;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox<Alumno> jcbxAlumnos;
    private javax.swing.JLabel jlbAlumno;
    private javax.swing.JLabel jlbFormularioDeInscripcion;
    private javax.swing.JLabel jlbListadoDeMaterias;
    private javax.swing.JRadioButton jradiobtInscriptas;
    private javax.swing.JRadioButton jradiobtNoInscriptas;
    private javax.swing.JTable jtableMaterias;
    // End of variables declaration//GEN-END:variables
}
